FROM node:16-alpine
WORKDIR /app
RUN npm install http-server -g
# RUN npm install pg -g
# RUN npm install browserify -g
CMD [ "npx", "http-server"]

# "browserify pg.js -o bo.js",
# "browserify "./database/pg.js" -o "./database/index.js"",
# CMD ["npx","http-server"]
